name: sustain

on:
  issues:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Maybe move an issue to the project board
      uses: actions/github-script@0.4.0
      uses: actions/core@1.1.0
      with: 
        github-token: ${{secrets.GITHUB_TOKEN}}
        project-id: ${{secrets.PROJECT_ID}}
        script: |
            const core = require('@actions/core');
            const myInput = core.getInput('projectId', { required: true });
            
            console.log(context.issue.number)
            console.log(context.payload.label)
            
