name: sustain

on:
  issues:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Maybe move an issue to the project board
      uses: actions/github-script@0.4.0
      with: 
        github-token: ${{secrets.GITHUB_TOKEN}}
        project-id: ${{secrets.PROJECT_ID}}
        script: |            
            console.log(context.issue.number)
            console.log(context.payload.label)
            github.projects.createCard({
              column_id: "Bugs",
              content_id: context.issue.number,
              content_type: "Issue"
            })
            
