name: sustain

on:
  issues:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Maybe move an issue to the project board
      uses: actions/github-script@0.4.0
      with: 
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            console.log(context.repo.owner)
            console.log(context.repo.owner)
            console.log(context.eventName)
            
